## this is the all-in-one, standalone Discourse Docker container template
##
## After making changes to this file, you MUST rebuild
## /var/discourse/launcher rebuild app
##
## BE *VERY* CAREFUL WHEN EDITING!
## YAML FILES ARE SUPER SUPER SENSITIVE TO MISTAKES IN WHITESPACE OR ALIGNMENT!
## visit http://www.yamllint.com/ to validate this file as needed

templates:
  - "templates/postgres.template.yml"
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"
## Uncomment these two lines if you wish to add Lets Encrypt (https)
  #- "templates/web.ssl.template.yml"
  #- "templates/web.letsencrypt.ssl.template.yml"

## which TCP/IP ports should this container expose?
## If you want Discourse to share a port with another webserver like Apache or nginx,
## see https://meta.discourse.org/t/17247 for details
expose:
  - "80:80"   # http
  - "443:443" # https

params:
  db_default_text_search_config: "pg_catalog.english"

  ## Set db_shared_buffers to a max of 25% of the total memory.
  ## will be set automatically by bootstrap based on detected RAM, or you can override
  db_shared_buffers: "2048MB"

  ## can improve sorting performance, but adds memory usage per-connection
  #db_work_mem: "40MB"

  ## Which Git revision should this container use? (default: tests-passed)
  #version: tests-passed

env:
  LANG: en_US.UTF-8
  # DISCOURSE_DEFAULT_LOCALE: en

  ## How many concurrent web requests are supported? Depends on memory and CPU cores.
  ## will be set automatically by bootstrap based on detected CPUs, or you can override
  UNICORN_WORKERS: 2

  ## TODO: The domain name this Discourse instance will respond to
  ## Required. Discourse will not work with a bare IP number.
  DISCOURSE_HOSTNAME: amnimocicd.japaneast.cloudapp.azure.com

  ## Uncomment if you want the container to be started with the same
  ## hostname (-h option) as specified above (default "$hostname-$config")
  #DOCKER_USE_HOSTNAME: true

  ## TODO: List of comma delimited emails that will be made admin and developer
  ## on initial signup example 'user1@example.com,user2@example.com'
  DISCOURSE_DEVELOPER_EMAILS: 'muthukkumar@nichesoft.net'
  #DISCOURSE_DEVELOPER_USERNAME : subham
  #DISCOURSE_DEVELOPER_PASSWORD: "grttechgamer123"

  ## TODO: The SMTP mail server used to validate new accounts and send notifications
  # SMTP ADDRESS, username, and password are required
  # WARNING the char '#' in SMTP password can cause problems!
  #DISCOURSE_SMTP_ADDRESS: smtp.gmail.com
  DISCOURSE_SMTP_PORT: 587
  DISCOURSE_SMTP_USER_NAME: muthukkumar@nichesoft.net
  DISCOURSE_SMTP_PASSWORD: "Divipin!5566"
  #DISCOURSE_SMTP_ENABLE_START_TLS: true           # (optional, default true)
  DISCOURSE_SMTP_ADDRESS: smtp.gmail.com
  DISCOURSE_SMTP_PORT: 587
  DISCOURSE_SMTP_USER_NAME: muthukkumar@nichesoft.net
  DISCOURSE_SMTP_PASSWORD: "Divipin!5566"
  DISCOURSE_SMTP_ENABLE_START_TLS: true

  ## If you added the Lets Encrypt template, uncomment below to get a free SSL certificate
  #LETSENCRYPT_ACCOUNT_EMAIL: me@example.com

  ## The CDN address for this Discourse instance (configured to pull)
  ## see https://meta.discourse.org/t/14857 for details
  #DISCOURSE_CDN_URL: //discourse-cdn.example.com

## The Docker container is stateless; all data is stored in /shared
volumes:
  - volume:
      host: /var/discourse/shared/standalone
      guest: /shared
  - volume:
      host: /var/discourse/shared/standalone/log/var-log
      guest: /var/log

## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/MuthukkumarNicheSoft/CSS-plugin.git
          - git clone https://github.com/discourse/discourse-solved.git
          #- git clone https://github.com/gensub/discourse_email_attribute.git
          
## Any custom commands to run after building
run:
  - exec: echo "Beginning of custom commands"
  ## If you want to set the 'From' email address for your first registration, uncomment and change:
  ## After getting the first signup email, re-comment the line. It only needs to run once.
  #- exec: rails r "u = User.create!(username: '{{ subham }}', email: '{{ subham@nichesoft.net }}', password: ' {{ grttechgamer123 }}', admin: true)"
  #- exec: cd /var/www/discourse && rails r "SiteSetting.notification_email= 'subham@nichesoft.net'"
  #- exec: cp /shared/file.rb /var/www/discourse
  #- exec: 
  #      cd: /var/www/discourse && rails r file.rb
  - exec: cd /var/www/discourse && sudo -u discourse bundle install --deployment --without test --without development
  - exec: echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /user/.ssh/config
  - file:
      path: /user/.ssh/id_rsa
      chmod: 600
      contents: |
        -----BEGIN RSA PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-128-CBC,19EA4589000FE19E7F44F2E86FDA3990   
        LVu2mQftpz2WjPFOE6TO2ODMbv/5gbdKK2ou3HH0sW6E468ewQs4dbNN/VQ0ocVx
        7bxXEvdz6VDgkanHKDzUWmWvcO3tfy+1Mh4VtW7iHbOOREALKSG2kKzQXu4XgjX+
        DrKq2usPvs42ETgq3PbO3dBR6E+ROxOIHQNHeekNrakJvb2Tb5nsI4ysPALctOKO
        buJ0i1oXRuDV2JHMiypJeXrpl1KLWFCJqcgFc33cwTef1jyZAfkIyAp8+AjYZm4w
        B3iHGZ8zCnfvXm14k8RVW3rsZnzdRNEk32zdVQy2EFzxEvbwk7MuKM0462Yp7wGX
        1Fx6cihsnh10hE0LLctFEnskqs8fHfdtQUXFO79J9E1zdSsaASivjLDiJbZpVEld
        3gOvKhSUIftCH3Ufg6D2lHO2a+K75gqY5FPiml0XsdNKFB08m5+yRNXNp/keQDNR
        ZEoWD6NZKiDmSmqFdqG5g3js5rr/4qQWtqymmqR2PtH/iGsNB17W2TqdzUssL/S3
        yBCVqTxQyDqB8VWDjxJk4UTzniaMyEf7wphIK9+9zwHXKA50PtvJ2zZL0t/uxs8L
        AK0V49jYoby3gzOvCrXPcrky03PW2uSYyqmIV6j7n1Zh8h3Nt1JzH9m2wW58krYS
        7hVHxhtGib5I8zuO7aEgkJKH27GjgTJL1LE2j53sXbO0ahS4uAZyfT3VRFP9Y8Ck
        AyAmQ5Ere8XZYjOQlqvHwLvi6x/oASG/QpuX3McrfKdYJYL/vWU0zrzOFakH57XT
        apGDFbgg93CUfT8k4OEvcOe2e/kPNjda9jMf0a1Cdjdo0Fm+Om6bMFuUEiOxg9uo
        XDKqCEClGtODK2GTXbXWlha9OxvF3ubBYuP12IutM6V3k/NohmySD1fta9U9V9to
        e2cfHECnzmk0cmUr6hND9UPT5qLpWJEmkBIg9rwOpHB345jz8MYPBi86euLs1yf8
        uax/ePRFqQdy1FuPEU7cCbUrsbFwIyz/RT8OcFSiEeTFlLLeFzkHUbm3jfBETAUn
        YYfIwDTYlChXfKtas/RWJvFPWgJ+BFoQ5NYi4JxfBHRbwJq8wj5iR1RxgjQJV7zp
        GI+f39JrjeBLyiXDGZWBoRLKSwyBG0h4UiDPj3UiFE/8bEnXUAot2Grl5WWKQyr3
        YAgSXuzye+/qFYBsjJ7d7HxAZmogLLI/ix596pc1UZlZOnNhXJOL+TfN8EmeoNCP
        tRFY7MfE18akSWVKcD3YyZC8JaN0wV05SiqTKajb4kRH0ilBHV7cYPCLFuBYSP1X
        OROAP01oKlAo/SPjVHOExocbXhtsDpaFgjk7ZM45xTDqX9LKkbWA4tMeyoVCZpE7
        PPnS3hV3CLPZtOlGv2tT5N51MbyW+AN4/gSapO4Knn2kTxX5pbAe8poWsYgLDjqC
        7oY6zMVm1haYXYHzYYi3o+DTRXPoq1Vo01Q/bkut+npiviiRlZGvJ7iOHbrlJFhY
        T6H2GohspXEKoqdOjViveRji4HBB7A+5IsliE+HXpKv79690XP1jor08kh+5EfzJ
        2sSHhVH3TuAvJT13SKwjSn2Ggehn4pFYF+lv9hZ1O+9MLPCsq9NGGEkBB9DM4XYe
        -----END RSA PRIVATE KEY-----
  - file:
      path: /user/.ssh/id_rsa.pub
      chmod: 600
      contents: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKgU+rwoVvH9re6pPi2ECEdledqTS4qr4rFT+IbvNQkKGzXSz5HgKwQQsRe0rvjqVcVagIiwTv/Rre0Pz26UnFhkQdC87X22dI09RXMNmcTnmg9el57VYbrOBLxccHB04eBy/VYShRb9Q0FgNXfWFF0JncFPi9cJsKLI8HkZ9gkkESNZXDj5w7ZBf1oYOPuL6A1RyYrbujYGOXVydhtJ5j+XIFhEdjZYhBoeTrMIQ7J0Ralq5S9h46XZsKqVdlAM+ZEYcQm1cJKKbLljODKY21SWWy31dExYcriJKIfik966eVTKnYOeSgwTt+gzxk3TqJQRTZRwKw3oxU9V++SaF5 surendra@Nichesoft-31.local
  - exec: cd $home/plugins && git clone yec-addx@vs-ssh.visualstudio.com:v3/yec-addx/VAP%20Experience/Community%20Plugins
  - exec: cd $home && sudo -E -u discourse bundle exec rake db:migrate
  - exec: cd $home && rm -fr tmp/cache
  - exec: cd $home &&  sudo -E -u discourse bundle exec rake assets:precompile
  - exec: rm /user/.ssh/id_rsa
  - exec: rm /user/.ssh/id_rsa.pub
  - exec: echo "End of custom commands"
  
